### PR TITLE
Port Forward Added to Apollo

### PR DESCRIPTION
**Pull request by thiagomayllart**
Hello everyone,

I've added support for remote port forward. It works just like socks functionality. The whole traffic goes through the connection already established with the agent, so, if you forward an RDP/SSH/etc, it will act as a RDP through HTTP.

As mentioned, the traffic goes in a pretty similar way as the socks command: base64 string from the received bytes will be added to a dictionary in the new field of the json message (rportfwds) from/to the agent.

The rportfwd function supports multiple connections to the same port and multiple forwarded ports at the same time.

### CODE REVIEW

**Comment by djhohnstein** [comment]
Awesome! I'll have some time to review this and the other outstanding PR very soon and get it tested and integrated. I'll keep you posted. Well done!

**Comment by djhohnstein** [comment]
JFYI, I haven't lost sight of this. We're still discussing port forwarding and general SOCKS stuff. Thank you for continuing to update your PR!

**Comment by thiagomayllart** [comment]
Thank you!! No worries!! I have fixed some issues related to the order of the packets. Some packets were arriving out of order, so some protocols like RDP would present some errors since I one HTTP response could be processed before another, causing encryption errors like. I have just added a way to sort the messages in the order they come from the socket.

**Comment by djhohnstein** [comment]
I'll try to get to this today 😄

**Pull request closed without merging**
